name: Go
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

        # This is used since the above action does not set it for now
        #  Remove once https://github.com/actions/setup-go/issues/27 is fixed
      - name: Set GOBIN
        run: export PATH=${PATH}:`go env GOPATH`/bin

      - name: Tools
        run: make tools

      - name: Build
        run: make build

      - name: Test
        run: make test
